#!/usr/bin/env python3
"""Emit the interactive version of the latency-vs-throughput chart.

Same data as the static PNG (results/capacity_table.tsv), so the two cannot
disagree. Interactivity earns its place on this particular chart for three
reasons the static one cannot solve:

  * seven series overlap in the 1-2 ms cluster -> click the legend to isolate one
  * the plot shows shape but not values      -> hover for fps, latency, concurrency
  * D's 74 ms tail compresses the interesting -> box-zoom into 1-4 ms
    region, which is why the x axis is log

This emits a SCRIPT, not a standalone page, and the chart is drawn directly into
the docs page. The earlier version used an <iframe>, which was wrong twice over:

  1. An iframe is a separate document with its own canvas, so it rendered as a
     white box on the dark theme. `color-scheme: light dark` only half-fixed it
     -- that follows the OS preference, but Material's palette toggle is
     independent of the OS, so anyone who clicked the moon on a light machine
     still got a white box.
  2. Its src is raw HTML, which MkDocs does not rewrite, so the relative depth
     had to be right by hand -- and once wasn't, silently loading the 404 page.

Drawing in-page removes both: the plot sits on the page's own background, and
the theme is read from Material's `data-md-color-scheme` and re-read whenever
the reader toggles it.

Plotly is loaded from CDN; nothing is vendored. GitHub markdown does not execute
JavaScript, so the committed .md keeps the PNG and only the site gets this --
scripts/prepare_site.py does the swap at build time.

Usage:  python3 scripts/make_interactive.py [repo_root]
Output: docs/img/pareto_chart.js
"""
import csv
import json
import os
import sys
from collections import defaultdict

REPO = sys.argv[1] if len(sys.argv) > 1 else "."
OUT = os.path.join(REPO, "docs", "img", "pareto_chart.js")

COLORS = {
    "A1": "#9aa0a6", "A2": "#e8710a", "B1": "#9aa0a6", "B2": "#1a73e8",
    "C1": "#9aa0a6", "C2": "#12a150", "D": "#a142f4",
}
LABELS = {
    "A1": "A1 · C++ TRT, CPU path", "A2": "A2 · C++ TRT, full-CUDA",
    "B1": "B1 · Triton + C++, raw gRPC", "B2": "B2 · Triton + C++, CUDA-shm",
    "C1": "C1 · Triton + PyTorch", "C2": "C2 · Triton + numpy, sys-shm",
    "D": "D · Triton async, batch-8",
}
ORDER = ["A2", "D", "B2", "C2", "A1", "B1", "C1"]

rows = defaultdict(list)
with open(os.path.join(REPO, "results", "capacity_table.tsv")) as f:
    for r in csv.DictReader(f, delimiter="\t"):
        rows[r["flow"]].append((int(r["concurrency"]), float(r["fps"]),
                                float(r["lat_p50_ms"])))
for k in rows:
    rows[k].sort()

traces = []
for flow in ORDER:
    pts = rows[flow]
    traces.append({
        "x": [p[2] for p in pts],
        "y": [p[1] for p in pts],
        "text": ["concurrency %d" % p[0] for p in pts],
        "name": LABELS[flow],
        "mode": "lines+markers",
        "type": "scatter",
        "line": {"color": COLORS[flow], "width": 2},
        "marker": {"color": COLORS[flow], "size": 8},
        "hovertemplate": ("<b>%s</b><br>%%{text}<br>"
                          "%%{y:.0f} fps<br>%%{x:.2f} ms p50<extra></extra>") % flow,
    })

# Everything here is theme-independent; colours are applied at draw time.
layout = {
    "title": {"text": "Latency vs throughput — drag to zoom, click the legend to isolate a flow",
              "font": {"size": 15}},
    "xaxis": {"title": {"text": "per-frame latency p50 (ms, log) — lower is better"},
              "type": "log", "zeroline": False,
              "tickvals": [1, 2, 5, 10, 20, 50],
              "ticktext": ["1", "2", "5", "10", "20", "50"]},
    "yaxis": {"title": {"text": "throughput (fps) — higher is better"},
              "zeroline": False},
    "shapes": [{"type": "line", "x0": 33.3, "x1": 33.3, "yref": "paper", "y0": 0, "y1": 1,
                "line": {"width": 1, "dash": "dash"}}],
    "annotations": [{"x": 1.523, "y": 0.05, "xref": "x", "yref": "paper",
                     "text": "30 FPS budget (33.3 ms)", "showarrow": False,
                     "font": {"size": 10}, "xanchor": "left"}],
    "hovermode": "closest",
    "legend": {"font": {"size": 11}, "bgcolor": "rgba(0,0,0,0)"},
    "margin": {"l": 70, "r": 20, "t": 55, "b": 60},
    # Transparent on both counts, so the plot sits on the page's own background
    # whatever that background happens to be.
    "paper_bgcolor": "rgba(0,0,0,0)",
    "plot_bgcolor": "rgba(0,0,0,0)",
}

JS = """/* Generated by scripts/make_interactive.py - do not edit by hand. */
(function () {
  "use strict";
  var TRACES = %s;
  var LAYOUT = %s;
  var CONFIG = {responsive: true, displaylogo: false,
                modeBarButtonsToRemove: ["lasso2d", "select2d"]};

  /* Material's palette toggle sets data-md-color-scheme="slate" on <body>. It is
     deliberately independent of the OS preference, so read the attribute rather
     than prefers-color-scheme, or a reader who clicks the moon on a light
     machine gets light-theme text on a dark page. */
  function palette() {
    var slate = document.body.getAttribute("data-md-color-scheme") === "slate";
    return slate
      ? {fg: "#c6cad2", grid: "rgba(255,255,255,0.14)"}
      : {fg: "#5b6168", grid: "rgba(0,0,0,0.12)"};
  }

  function draw(el) {
    var c = palette();
    var L = JSON.parse(JSON.stringify(LAYOUT));
    L.font = {color: c.fg};
    L.xaxis.gridcolor = L.yaxis.gridcolor = c.grid;
    L.xaxis.linecolor = L.yaxis.linecolor = c.grid;
    L.shapes[0].line.color = c.fg;
    L.annotations[0].font.color = c.fg;
    Plotly.react(el, TRACES, L, CONFIG);
  }

  function init() {
    var el = document.getElementById("pareto-chart");
    if (!el || typeof Plotly === "undefined") { return; }
    draw(el);
    if (!el.dataset.themeBound) {
      el.dataset.themeBound = "1";
      new MutationObserver(function () { draw(el); }).observe(
        document.body, {attributes: true, attributeFilter: ["data-md-color-scheme"]});
    }
  }

  /* Runs on first load and again after Material's instant navigation swaps the
     page content in without a reload. */
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
"""

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write(JS % (json.dumps(traces), json.dumps(layout)))
print("wrote", os.path.relpath(OUT, REPO))
